permissions:
  contents: read

name: GA dataset view count report

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "cf environment"
        required: true
        type: choice
        default: "development"
        options:
          - development
          - staging
          - prod
  schedule:
    - cron: "0 0 2 * *" # Runs at 00:00 UTC on 2nd day of the month - to account for GA4 reporting latency

env:
  TARGET_ENV: ${{ inputs.environment || 'development' }}

jobs:
  dataset-view-count:
    runs-on: ubuntu-latest
    name: generate dataset view count report
    environment: ${{ env.TARGET_ENV }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: run task
        uses: cloud-gov/cg-cli-tools@main
        with:
          command: >
            cf run-task datagov-harvest --name update_dataset_view_count
            --command "python scripts/update_dataset_view_count.py"
          cf_org: gsa-datagov
          cf_space: ${{ env.TARGET_ENV }}
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
